apiVersion: v1
kind: Service
metadata:
  name: argocd-jenkins-k8s-cicd
spec:
  type: NodePort
  selector:
    app: argocd-jenkins-k8s-cicd
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30080

